### Get all notes
GET http://localhost:3001/api/notes

###

### Create a new note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "VS Code REST client is convenient",
    "important": true
}

###

### Try creating an invalid note (missing content)
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Ensure that everything still works",
    "important": true
}